//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class VehicleMake
	{
		public VehicleMake()
		{
			this.VehicleModel = new HashSet<VehicleModel>();
		}
	
		public int Id { get; set; }
		[Display(Name="Make")]
		public string Name { get; set; }
	
		public virtual ICollection<VehicleModel> VehicleModel { get; set; }
	}
}
